version: '3.4'

services:
  stafftimetableapi:
    image: ${DOCKER_REGISTRY-}stafftimetableapi
    container_name: StaffTimetableApi
    build:
      context: .
      dockerfile: StaffTimeTableAPI/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - stafftimetableapidb
  
  stafftimetableapidb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: StaffTimetableDB
    hostname: stafftimetableapidb
    restart: on-failure
    environment:
      SA_PASSWORD: "aChFfXrQXVi0MTK8cf8q"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    expose:
      - 1433
  
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    container_name: KeyCloak
    hostname: keycloak
    restart: on-failure
    environment:
      KEYCLOAK_ADMIN: master
      KEYCLOAK_ADMIN_PASSWORD: master
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
    volumes:
      - ./resources/keycloak/import/realm-export.json:/opt/keycloak/data/import/realm.json
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master" ]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s
  
