version: '3.4'

services:
  stafftimetableapi:
    image: ${DOCKER_REGISTRY-}stafftimetableapi
    container_name: stafftimetableapi
    hostname: stafftimetableapi
    build:
      context: .
      dockerfile: StaffTimeTableAPI/Dockerfile
    ports:
      - "8000:80"
    restart: unless-stopped
    depends_on:
      - stafftimetableapidb
      - keycloak
      - seq
    networks:
      - appnet
      - internet
  
  stafftimetableapidb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: stafftimetableapidb
    hostname: stafftimetableapidb
    restart: on-failure
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "aChFfXrQXVi0MTK8cf8q"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    expose:
      - 1433
    networks:
      - appnet
  
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    container_name: keycloak
    hostname: keycloak
    restart: on-failure
    environment:
      KEYCLOAK_ADMIN: master
      KEYCLOAK_ADMIN_PASSWORD: master
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
    volumes:
      - ./resources/keycloak/import/realm-export.json:/opt/keycloak/data/import/realm.json
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master" ]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s
    networks:
      - appnet
      - internet
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    networks:
      - appnet
      - internet
  
networks:
  internet:
    driver: bridge
  appnet:
    driver: bridge